### ISSUE TITLE
Execute commands on build.write hook instead of bundle.generate

### ISSUE THREAD

**Issue by jitendersandhu** [audinue/rollup-plugin-execute#1]
Hi @audinue ,

Thanks for the awesome plugin! it really helped me to use it to copy the generated build files from destination directory to a different directory to serve, which `rollup-plugin-copy` didn't provide ;).

I was wondering if instead of `ongenerate` (`bundle.generate`), we can use `onwrite` (`bundle.write`) hook to execute the commands or have the trigger supplied to the plugin (either `ongenerate` or `onwrite`) and fall back to `ongenerate` if not supplied. This will make sure it executes once the files are written to the destination directory.

Refer to below links for more info on rollup hooks:

https://github.com/rollup/rollup/pull/353#issuecomment-182887979
https://github.com/rollup/rollup/pull/742

Thanks!

**Comment by audinue** [comment]
I didn't see any difference with `onwrite` and `ongenerate`.

You can try it out here: [onwrite](https://github.com/audinue/rollup-plugin-execute/tree/onwrite)

**Comment by jitendersandhu** [comment]
Thanks for the quick response! I am able to use the alternative of storing the build output in the folder where i wanted by using `rollem` multiple-entry rollup wrapper. Hence, closing this issue.

**Comment by audinue** [comment]
Good for you 😄
