### ISSUE TITLE
Block until command returns

### ISSUE THREAD

**Issue by pjebs** [audinue/rollup-plugin-execute#7]
`execute('gopherjs build ./app/cron_screen -m -o ./app/cron_screen_temp.js'),`

It would be good if this plugin blocks until the command it is executing returns with an error code etc.

Right now, it _seems_ to run the command and go to next command.

**Comment by pjebs** [comment]
```
import * as childx from 'child_process'
	childx.execSync(path);
```

**Comment by pjebs** [comment]
```
child_process.spawnSync(command[, args][, options])
```

instead of `spawn()` which is what this library uses.

Or perhaps make it an option for backwards compatibility.

**Comment by ch-stuart** [comment]
I agree, I just discovered this is the cause of a bug where that's built with a grunt plugin is sometimes not being included in my Rollup-based build.

**Comment by ch-stuart** [comment]
I believe this is resolved by https://github.com/audinue/rollup-plugin-execute/pull/8.

Thanks for the fix!
